### ISSUE TITLE
device precision problem

### ISSUE THREAD

**Issue by LittleByLittle2** [slobdell/kalman-filter-example#1]
Hi Slobdell,

Would you mind tell me what kind of IMU do you using for your project? I use the IMU from my cell phone, the result is terrible and the direction is bad.

Best,
Yu

**Comment by JoseRFJuniorLLMs** [comment]
Estou com a mesma duvida !!

**Comment by LittleByLittle2** [comment]
> Estou com a mesma duvida !!

The code has bugs and does not use it. Good luck~
